import Foundation

@Observable
@MainActor
final class UsernamePickerViewModel {

    var username     = ""
    var isSubmitting = false
    var errorMessage: String?

    let isChange: Bool

    /// Tracks the most recent system-generated default. Used to determine if
    /// a 409 should silently retry with a fresh suggestion (the user kept the
    /// pre-filled name) vs. surface an error (the user typed their own choice).
    private var generatedDefault: String?
    private let api = APIClient()

    init(isChange: Bool = false) {
        self.isChange = isChange
    }

    var canSubmit: Bool {
        !isSubmitting && localValidate(normalizedUsername) == nil
    }

    /// Inline format error shown under the input — `nil` when input is empty
    /// or valid. Kept separate from `errorMessage` (server-side errors).
    var formatError: String? {
        guard !normalizedUsername.isEmpty else { return nil }
        return localValidate(normalizedUsername)
    }

    // MARK: - Prefill

    /// Pre-populates the text field with a single ready-to-submit username.
    /// Order: existing guest username → server suggestion → client fallback.
    func prefillIfNeeded(guestStore: GuestStore?) async {
        guard username.isEmpty else { return }

        // Prefer an existing guest-mode username (user picked it themselves)
        if !isChange,
           let guest = guestStore?.localUsername?.trimmingCharacters(in: .whitespacesAndNewlines),
           !guest.isEmpty,
           localValidate(guest) == nil {
            username = guest
            // Don't mark as auto-generated — the user typed this; on 409 we
            // surface the error rather than silently swap their choice.
            return
        }

        let suggestion = await fetchSuggestion() ?? Self.clientGenerated()
        guard username.isEmpty else { return }
        username = suggestion
        generatedDefault = suggestion
    }

    // MARK: - Typing

    func onUsernameChanged(_ newValue: String) {
        let trimmed = newValue.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed != newValue {
            username = trimmed
        }
        errorMessage = nil

        // If the user diverged from the pre-filled default, treat as user-typed
        // so a future 409 surfaces an error instead of swapping their text.
        if let def = generatedDefault, trimmed != def {
            generatedDefault = nil
        }
    }

    // MARK: - Submit

    func submit(authManager: AuthManager) async {
        guard canSubmit else { return }
        await performSubmit(authManager: authManager, autoRetriesRemaining: 2)
    }

    private func performSubmit(authManager: AuthManager, autoRetriesRemaining: Int) async {
        let candidate = normalizedUsername
        let isAutoGenerated = (candidate == generatedDefault)
        isSubmitting = true
        errorMessage = nil
        defer { isSubmitting = false }

        do {
            if isChange {
                try await authManager.changeUsername(candidate)
            } else {
                try await authManager.setUsername(candidate)
            }
        } catch {
            let isTaken: Bool = {
                if case APIError.serverError(409, _) = error { return true }
                if case APIError.serverError(400, let msg) = error,
                   let m = msg, m.lowercased().contains("unique constraint") { return true }
                return false
            }()

            if isTaken {
                if isAutoGenerated && autoRetriesRemaining > 0 {
                    // The user hasn't customized the prefill — silently swap
                    // to a fresh available suggestion and retry. Apple reviewers
                    // get a one-tap path to a working account.
                    let fresh = await fetchSuggestion() ?? Self.clientGenerated()
                    username = fresh
                    generatedDefault = fresh
                    await performSubmit(authManager: authManager, autoRetriesRemaining: autoRetriesRemaining - 1)
                    return
                }
                errorMessage = "Username already taken — please choose another."
            } else if case APIError.serverError(400, let msg) = error, let m = msg {
                errorMessage = m
            } else {
                errorMessage = error.localizedDescription
            }
        }
    }

    // MARK: - Suggestion fetch

    private func fetchSuggestion() async -> String? {
        do {
            let response: SuggestionsResponse = try await api.request(.suggestUsernames)
            return response.suggestions.first
        } catch {
            return nil
        }
    }

    private static let adjectives = [
        "Red", "Blue", "Silver", "Golden", "Swift",
        "Iron", "Midnight", "Rapid", "Turbo", "Carbon",
        "Neon", "Apex", "Delta", "Storm", "Phantom",
    ]
    private static let nouns = [
        "Falcon", "Wolf", "Viper", "Hawk", "Tiger",
        "Fox", "Eagle", "Shark", "Racer", "Pilot",
        "Driver", "Apex", "Vector", "Turbo", "Nitro",
    ]

    private static func clientGenerated() -> String {
        let adj  = adjectives.randomElement() ?? "Apex"
        let noun = nouns.randomElement() ?? "Racer"
        let num  = Int.random(in: 10...99)
        return "\(adj)\(noun)\(num)"
    }

    // MARK: - Private

    private var normalizedUsername: String {
        username.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private func localValidate(_ value: String) -> String? {
        if value.count < 3 { return "Username must be at least 3 characters." }
        if value.count > 20 { return "Username must be 20 characters or fewer." }
        if value.range(of: "^[A-Za-z0-9]+$", options: .regularExpression) == nil {
            return "Only letters and numbers allowed."
        }
        return nil
    }
}

private struct SuggestionsResponse: Decodable, Sendable {
    let suggestions: [String]
}
